### ISSUE TITLE
Can't find components folder

### ISSUE THREAD

**Issue by carl87gt** [woxdak/full-stack-ecommerce-website#1]
When I try to build I get a bunch of errors like:

` src/app/app.module.ts:15:34 - error TS2307: Cannot find module './components/contact/contact.component' or its corresponding type declarations.`

Looks like the project is missing the components folder? Perhaps it was never added with git?

**Comment by woxdak** [comment]
Thank you for pointing that out!
At first, I added all the files manually so I missed some folders.
I just fixed it and I added all the files in the new repository using git.
https://github.com/woxdak/full-ecommerce
The Angular site should work by now!

**Comment by carl87gt** [comment]
Hey thanks!

I did see you added some but I still show these as not found and don't see them in the project . . .

[cid:397a7ab9-890c-467b-bfdc-768caf5996ec]
________________________________

**Comment by woxdak** [comment]
Dear Mr. Carl,
I push all the files in a new repository. You could check it out here.
https://github.com/woxdak/full-ecommerce/tree/main/03-front-end/angular-ecommerce/src/app
So right now, there are two repositories pointing to the same project.
https://github.com/woxdak/full-ecommerce
https://github.com/woxdak/full-stack-ecommerce-website
Please let me know if I could assist anything else!
Warren
